#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v21
# autospec commit: 5424026
#
# Source0 file verified with key 0xCEFAC8EAAF17519D (julliard@winehq.org)
#
Name     : vkd3d
Version  : 1.14
Release  : 14
URL      : https://dl.winehq.org/vkd3d/source/vkd3d-1.14.tar.xz
Source0  : https://dl.winehq.org/vkd3d/source/vkd3d-1.14.tar.xz
Source1  : https://dl.winehq.org/vkd3d/source/vkd3d-1.14.tar.xz.sign
Source2  : CEFAC8EAAF17519D.pkey
Summary  : The vkd3d 3D Graphics Library
Group    : Development/Tools
License  : LGPL-2.1
Requires: vkd3d-bin = %{version}-%{release}
Requires: vkd3d-lib = %{version}-%{release}
Requires: vkd3d-license = %{version}-%{release}
BuildRequires : SPIRV-Headers-dev
BuildRequires : SPIRV-Tools
BuildRequires : SPIRV-Tools-dev
BuildRequires : Vulkan-Headers-dev
BuildRequires : Vulkan-Loader-dev
BuildRequires : Vulkan-Loader-dev32
BuildRequires : bison
BuildRequires : buildreq-configure
BuildRequires : doxygen
BuildRequires : file
BuildRequires : flex
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : gnupg
BuildRequires : llvm-dev
BuildRequires : ncurses-dev
BuildRequires : ncurses-dev32
BuildRequires : perl
BuildRequires : pkg-config
BuildRequires : pkgconfig(32SPIRV-Tools-shared)
BuildRequires : pkgconfig(32egl)
BuildRequires : pkgconfig(32xcb)
BuildRequires : pkgconfig(32xcb-event)
BuildRequires : pkgconfig(32xcb-icccm)
BuildRequires : pkgconfig(32xcb-keysyms)
BuildRequires : pkgconfig(SPIRV-Tools-shared)
BuildRequires : pkgconfig(egl)
BuildRequires : pkgconfig(ncurses)
BuildRequires : pkgconfig(opengl)
BuildRequires : pkgconfig(xcb)
BuildRequires : pkgconfig(xcb-event)
BuildRequires : pkgconfig(xcb-icccm)
BuildRequires : pkgconfig(xcb-keysyms)
BuildRequires : sed
BuildRequires : wine-bin
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
=============================
The vkd3d 3D Graphics Library
=============================

%package bin
Summary: bin components for the vkd3d package.
Group: Binaries
Requires: vkd3d-license = %{version}-%{release}

%description bin
bin components for the vkd3d package.


%package dev
Summary: dev components for the vkd3d package.
Group: Development
Requires: vkd3d-lib = %{version}-%{release}
Requires: vkd3d-bin = %{version}-%{release}
Provides: vkd3d-devel = %{version}-%{release}
Requires: vkd3d = %{version}-%{release}

%description dev
dev components for the vkd3d package.


%package dev32
Summary: dev32 components for the vkd3d package.
Group: Default
Requires: vkd3d-lib32 = %{version}-%{release}
Requires: vkd3d-bin = %{version}-%{release}
Requires: vkd3d-dev = %{version}-%{release}

%description dev32
dev32 components for the vkd3d package.


%package lib
Summary: lib components for the vkd3d package.
Group: Libraries
Requires: vkd3d-license = %{version}-%{release}

%description lib
lib components for the vkd3d package.


%package lib32
Summary: lib32 components for the vkd3d package.
Group: Default
Requires: vkd3d-license = %{version}-%{release}

%description lib32
lib32 components for the vkd3d package.


%package license
Summary: license components for the vkd3d package.
Group: Default

%description license
license components for the vkd3d package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) CEFAC8EAAF17519D' gpg.status
%setup -q -n vkd3d-1.14
cd %{_builddir}/vkd3d-1.14
pushd ..
cp -a vkd3d-1.14 build32
popd
pushd ..
cp -a vkd3d-1.14 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1733424778
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static --with-spirv-tools \
--enable-tests
make  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig:/usr/share/pkgconfig"
ASFLAGS="${CLEAR_INTERMEDIATE_ASFLAGS}${CLEAR_INTERMEDIATE_ASFLAGS:+ }--32"
CFLAGS="${CLEAR_INTERMEDIATE_CFLAGS}${CLEAR_INTERMEDIATE_CFLAGS:+ }-m32 -mstackrealign"
CXXFLAGS="${CLEAR_INTERMEDIATE_CXXFLAGS}${CLEAR_INTERMEDIATE_CXXFLAGS:+ }-m32 -mstackrealign"
LDFLAGS="${CLEAR_INTERMEDIATE_LDFLAGS}${CLEAR_INTERMEDIATE_LDFLAGS:+ }-m32 -mstackrealign"
%configure --disable-static --with-spirv-tools \
--enable-tests   --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static --with-spirv-tools \
--enable-tests
make  %{?_smp_mflags}
popd
%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1733424778
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/vkd3d
cp %{_builddir}/vkd3d-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/vkd3d/01a6b4bf79aca9b556822601186afab86e8c4fbf || :
export GOAMD64=v2
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
if [ -d %{buildroot}/usr/share/pkgconfig ]
then
pushd %{buildroot}/usr/share/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/vkd3d-compiler
/V3/usr/bin/vkd3d-dxbc
/usr/bin/vkd3d-compiler
/usr/bin/vkd3d-dxbc

%files dev
%defattr(-,root,root,-)
/usr/include/vkd3d/vkd3d.h
/usr/include/vkd3d/vkd3d_d3d12.h
/usr/include/vkd3d/vkd3d_d3d12sdklayers.h
/usr/include/vkd3d/vkd3d_d3d12shader.h
/usr/include/vkd3d/vkd3d_d3d9types.h
/usr/include/vkd3d/vkd3d_d3dcommon.h
/usr/include/vkd3d/vkd3d_d3dcompiler.h
/usr/include/vkd3d/vkd3d_d3dcompiler_types.h
/usr/include/vkd3d/vkd3d_d3dx9shader.h
/usr/include/vkd3d/vkd3d_dxgibase.h
/usr/include/vkd3d/vkd3d_dxgiformat.h
/usr/include/vkd3d/vkd3d_shader.h
/usr/include/vkd3d/vkd3d_types.h
/usr/include/vkd3d/vkd3d_utils.h
/usr/include/vkd3d/vkd3d_windows.h
/usr/lib64/libvkd3d-shader.so
/usr/lib64/libvkd3d-utils.so
/usr/lib64/libvkd3d.so
/usr/lib64/pkgconfig/libvkd3d-shader.pc
/usr/lib64/pkgconfig/libvkd3d-utils.pc
/usr/lib64/pkgconfig/libvkd3d.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libvkd3d-shader.so
/usr/lib32/libvkd3d-utils.so
/usr/lib32/libvkd3d.so
/usr/lib32/pkgconfig/32libvkd3d-shader.pc
/usr/lib32/pkgconfig/32libvkd3d-utils.pc
/usr/lib32/pkgconfig/32libvkd3d.pc
/usr/lib32/pkgconfig/libvkd3d-shader.pc
/usr/lib32/pkgconfig/libvkd3d-utils.pc
/usr/lib32/pkgconfig/libvkd3d.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libvkd3d-shader.so.1.12.0
/V3/usr/lib64/libvkd3d-utils.so.1.6.0
/V3/usr/lib64/libvkd3d.so.1.14.0
/usr/lib64/libvkd3d-shader.so.1
/usr/lib64/libvkd3d-shader.so.1.12.0
/usr/lib64/libvkd3d-utils.so.1
/usr/lib64/libvkd3d-utils.so.1.6.0
/usr/lib64/libvkd3d.so.1
/usr/lib64/libvkd3d.so.1.14.0

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libvkd3d-shader.so.1
/usr/lib32/libvkd3d-shader.so.1.12.0
/usr/lib32/libvkd3d-utils.so.1
/usr/lib32/libvkd3d-utils.so.1.6.0
/usr/lib32/libvkd3d.so.1
/usr/lib32/libvkd3d.so.1.14.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/vkd3d/01a6b4bf79aca9b556822601186afab86e8c4fbf
